### ISSUE TITLE
Neverzovat adresář .pio

### ISSUE THREAD

**Issue by yaqwsx** [RoboticsBrno/BlackBox_library#2]
Adresář .pio by se neměl verzovat - obsahuje vygenerované soubory, které mohou být platformově závislé a může to způsobit komplikace s kompilací na jiném systému. Zároveň naprosto zbytečně nafukuje velikost repozitáře.

**Comment by JarekParal** [comment]
To ale asi řeší poslední commit: https://github.com/RoboticsBrno/BlackBox_library/pull/1/files#diff-a084b794bc0759e7a6b77810e01874f2

Jen tam jeden soubor ještě zůstal.
Asi by bylo vhodné přidat i složku `.vscode` do `.gitignore`.

**Comment by haberturdeur** [comment]
Ještě něco by se nemělo verzovat?

**Comment by JarekParal** [comment]
Asi ne.
